### ISSUE TITLE
Solution Explorer

### ISSUE THREAD

**Issue by sec13b** [mertdas/RedPersist#2]
![image](https://github.com/user-attachments/assets/f11889c4-11c5-4903-891f-f5e93a59a16b)

**Comment by mertdas** [comment]
![image](https://github.com/user-attachments/assets/c01ec195-8e4d-4acc-af55-d172ef0e350c)

![image](https://github.com/user-attachments/assets/d42805a8-e7a5-431d-a5fa-cd6ecf8032a6)


Works well on my side

**Comment by sec13b** [comment]
i just try with:
dotnet add package Costura.Fody --version 3.3.3 
dotnet add package TaskScheduler --version 2.8.11

same cand build

**Comment by mertdas** [comment]
Load the Visual Studio project up and go to "Tools" > "NuGet Package Manager" > "Package Manager Settings"
Open "NuGet Package Manager" > "Package Sources"

Install the Fody
Install-Package Costura.Fody -Version 3.3.3

Install the Taskscheduler
Install-Package TaskScheduler -Version 2.8.11

**Comment by sec13b** [comment]
i did :
Load the Visual Studio project up and go to "Tools" > "NuGet Package Manager" > "Package Manager Settings"
Open "NuGet Package Manager" > "Package Sources"
Install-Package Costura.Fody -Version 3.3.3
Install-Package TaskScheduler -Version 2.8.11

![image](https://github.com/user-attachments/assets/29185c92-1c39-4f87-847d-0731b8ab2cfb)

**Comment by sec13b** [comment]
![image](https://github.com/user-attachments/assets/f447a346-2d36-49e1-b396-a666e91c2271)

**Comment by mertdas** [comment]
I see SharpLateral,

If you are doing this in the RedPersist project, there will be no problem.

Nugets are added and compiled without any problems on my side.

**Comment by mertdas** [comment]
![image](https://github.com/user-attachments/assets/0cee9d27-f01f-4b9b-ae71-1d0e5077f5ef)

**Comment by sec13b** [comment]
i want test both

**Comment by sec13b** [comment]
finally work for RedPersist.

Build started at 7:21 AM...
1>------ Build started: Project: RedPersist, Configuration: Release Any CPU ------
1>MSBUILD : warning : Fody: Could not find a FodyWeavers.xml file at the project level (C:\Users\test\Downloads\RedPersist-main\RedPersist). A default file has been created. Please review the file and add it to your project.
1>  RedPersist -> C:\Users\test\Downloads\RedPersist-main\RedPersist\bin\Release\RedPersist.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 7:21 AM and took 04.898 seconds ==========

**Comment by sec13b** [comment]
for SharpLateral , same error.

**Comment by sec13b** [comment]
no offense , can you upload  SharpLateral  to gofile.io

**Comment by mertdas** [comment]
Please open your SharpLateral related issues under SharpLateral repo
